In [2]:
!pip install tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/93/21/9b035a4f823d6aee2917c75415be9a95861ff3d73a0a65e48edbf210cec1/tensorflow-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.15.0 from https://files.pythonhosted.org/packages/4c/48/1a5a15517f18eaa4ff8d598b1c000300b20c1bb0e624539d702117a0c369/tensorflow_intel-2.15.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     ---------------------------------------- 57.5

   -------------------------- ------------- 16.4/24.4 MB 14.6 MB/s eta 0:00:01
   --------------------------- ------------ 17.0/24.4 MB 14.6 MB/s eta 0:00:01
   ---------------------------- ----------- 17.6/24.4 MB 14.2 MB/s eta 0:00:01
   ------------------------------ --------- 18.4/24.4 MB 14.2 MB/s eta 0:00:01
   ------------------------------ --------- 18.8/24.4 MB 13.6 MB/s eta 0:00:01
   -------------------------------- ------- 19.7/24.4 MB 14.2 MB/s eta 0:00:01
   -------------------------------- ------- 20.2/24.4 MB 14.2 MB/s eta 0:00:01
   --------------------------------- ------ 20.3/24.4 MB 13.9 MB/s eta 0:00:01
   --------------------------------- ------ 20.7/24.4 MB 13.6 MB/s eta 0:00:01
   ---------------------------------- ----- 21.1/24.4 MB 12.8 MB/s eta 0:00:01
   ----------------------------------- ---- 21.6/24.4 MB 12.6 MB/s eta 0:00:01
   ----------------------------------- ---- 21.9/24.4 MB 12.4 MB/s eta 0:00:01
   ------------------------------------ --- 22.5/24.

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [7]:
voc_size = 10000

In [8]:
onehot_repr = [one_hot(words, voc_size) for words in sent]
print(onehot_repr)

[[7336, 7918, 9282, 8308], [7336, 7918, 9282, 2600], [7336, 1378, 9282, 798], [1033, 5942, 7102, 9925, 6116], [1033, 5942, 7102, 9925, 5407], [4359, 7336, 7719, 9282, 3618], [1032, 8426, 425, 9925]]


In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [13]:
import numpy as np

In [14]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen= sent_length)
print(embedded_docs)

[[   0    0    0    0 7336 7918 9282 8308]
 [   0    0    0    0 7336 7918 9282 2600]
 [   0    0    0    0 7336 1378 9282  798]
 [   0    0    0 1033 5942 7102 9925 6116]
 [   0    0    0 1033 5942 7102 9925 5407]
 [   0    0    0 4359 7336 7719 9282 3618]
 [   0    0    0    0 1032 8426  425 9925]]


In [11]:
dim = 10

In [15]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length = sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 76ms/step
[[[ 0.00012374 -0.0011225  -0.01509032 -0.04042367  0.01755803
    0.01389608  0.02735493 -0.02289918  0.02501662  0.00477998]
  [ 0.00012374 -0.0011225  -0.01509032 -0.04042367  0.01755803
    0.01389608  0.02735493 -0.02289918  0.02501662  0.00477998]
  [ 0.00012374 -0.0011225  -0.01509032 -0.04042367  0.01755803
    0.01389608  0.02735493 -0.02289918  0.02501662  0.00477998]
  [ 0.00012374 -0.0011225  -0.01509032 -0.04042367  0.01755803
    0.01389608  0.02735493 -0.02289918  0.02501662  0.00477998]
  [-0.03671772  0.02398701  0.0017367  -0.00962958  0.02145051
   -0.02088344 -0.02503659  0.03220599 -0.03153237 -0.02701085]
  [ 0.01806431 -0.03314469 -0.0491683   0.04410149  0.04169717
    0.04346026 -0.00817659  0.00169532 -0.0088734  -0.01911004]
  [ 0.01812899 -0.04669614 -0.00389646 -0.02492527 -0.04325832
   -0.00607865 -0.04924965  0.01529906 -0.01448263  0.01765716]
  [ 0.00073887 -0.01603075 -0.0036713  -0.04891029  0.01432